def openFile(file):
    currentFile = open(file)
    for i in currentFile:
        arr=i.split(',')
        print(arr)
        return arr

rubShorts = openFile('rubShorts.txt')
rubLongs = openFile('rubLongs.txt')
cadShorts = openFile('cadShorts.txt')
cadLongs = openFile('cadLongs.txt')
chfShorts = openFile('chfShorts.txt')
chfLongs = openFile('chfLongs.txt')
gbpShorts = openFile('gbpShorts.txt')
gbpLongs = openFile('gbpLongs.txt')
jpyShorts = openFile('jpyShorts.txt')
jpyLongs = openFile('jpyLongs.txt')
eurShorts = openFile('eurShorts.txt')
eurLongs = openFile('eurLongs.txt')
nzdShorts = openFile('nzdShorts.txt')
nzdLongs = openFile('nzdLongs.txt')
audShorts = openFile('audShorts.txt')
audLongs = openFile('audLongs.txt')
usdShorts = openFile('usdShorts.txt')
usdLongs = openFile('usdLongs.txt')
alhorts = openFile('alShorts.txt')
alLongs = openFile('alLongs.txt')
copperShorts = openFile('copperShorts.txt')
copperLongs = openFile('copperLongs.txt')
goldShorts = openFile('goldShorts.txt')
goldLongs = openFile('goldLongs.txt')
silverShorts = openFile('silverShorts.txt')
silverLongs = openFile('silverLongs.txt')
gasShorts = openFile('gasShorts.txt')
gasLongs = openFile('gasLongs.txt')
oilShorts = openFile('oilShorts.txt')
oilLongs = openFile('oilLongs.txt')
